### ISSUE TITLE
Remove superscript character from package file name

### ISSUE THREAD

**Issue by jimkring** [ralphieraccoon/Kinova-MICO2#1]
Hi @ralphieraccoon,

Could you please change the package name in your *.vip build spec to a regular "2" character instead of a superscript?

![image](https://user-images.githubusercontent.com/381432/165349602-27d3477d-e47c-4f2c-85a3-a248812ffbfb.png)

That would prevent some problems for VIPM.

Thanks,

-Jim
vipm.io team

**Comment by ralphieraccoon** [comment]
Done in ebc5edd.
